import modal

app = modal.App("officecli-create-ppt")

image = (
    modal.Image.debian_slim()
    .apt_install(
        "curl",
        "libicu-dev"
    )
    .pip_install(
        "python-pptx",
    )
    .run_commands(
        "curl -fsSL https://raw.githubusercontent.com/iOfficeAI/OfficeCLI/main/install.sh -o install.sh",
        "bash install.sh",

        # diagnostics
        "which officecli || true",
        "officecli --version || true",
        "dotnet --info || true",
        "ls -R /root/.local || true"
    )
)

OFFICECLI = "/root/.local/bin/officecli"


@app.function(image=image)
def create_ppt(title: str, slides: list[str]):
    """
    PPT-specific OfficeCLI adapter.

    The wider backend now routes through a generic export dispatcher, but PPTX
    generation continues to reuse this existing OfficeCLI implementation.
    """

    from io import BytesIO
    import subprocess
    from pathlib import Path
    from uuid import uuid4

    from pptx import Presentation

    ppt_path = f"/tmp/{uuid4()}.pptx"

    def run_officecli(*args):
        result = subprocess.run(
            [OFFICECLI, *args],
            capture_output=True,
            text=True
        )
        if result.returncode != 0:
            error_text = result.stderr or result.stdout or "Unknown OfficeCLI error"
            raise Exception(error_text)
        return result

    def build_ppt_locally():
        presentation = Presentation()

        title_slide_layout = presentation.slide_layouts[0]
        title_slide = presentation.slides.add_slide(title_slide_layout)
        title_slide.shapes.title.text = title

        if len(title_slide.placeholders) > 1:
            title_slide.placeholders[1].text = "Generated by RAG Document Analyzer"

        bullet_slide_layout = presentation.slide_layouts[1]

        for slide_text in slides:
            slide = presentation.slides.add_slide(bullet_slide_layout)
            slide.shapes.title.text = slide_text

            if len(slide.placeholders) > 1:
                slide.placeholders[1].text_frame.text = slide_text

        if not slides:
            slide = presentation.slides.add_slide(bullet_slide_layout)
            slide.shapes.title.text = "Summary"
            if len(slide.placeholders) > 1:
                slide.placeholders[1].text_frame.text = title

        buffer = BytesIO()
        presentation.save(buffer)
        buffer.seek(0)
        return buffer.read()

    def generated_ppt_is_valid(file_bytes):
        try:
            buffer = BytesIO(file_bytes)
            presentation = Presentation(buffer)
            expected_minimum_slides = max(1, len(slides)) + 1
            return len(presentation.slides) >= expected_minimum_slides
        except Exception:
            return False

    try:
        # Defensive cleanup in case OfficeCLI has a resident handle.
        subprocess.run(
            [OFFICECLI, "close", ppt_path],
            capture_output=True,
            text=True
        )

        run_officecli("create", ppt_path)
        run_officecli("add", ppt_path, "/", "--type", "slide")
        run_officecli(
            "add",
            ppt_path,
            "/slide[1]",
            "--type",
            "textbox",
            "--prop",
            f"text={title}"
        )

        for index, slide_text in enumerate(slides, start=2):
            run_officecli("add", ppt_path, "/", "--type", "slide")
            run_officecli(
                "add",
                ppt_path,
                f"/slide[{index}]",
                "--type",
                "textbox",
                "--prop",
                f"text={slide_text}"
            )

        run_officecli("save", ppt_path)
        run_officecli("close", ppt_path)

        with open(ppt_path, "rb") as file_handle:
            file_bytes = file_handle.read()

        if generated_ppt_is_valid(file_bytes):
            return file_bytes

        return build_ppt_locally()
    except Exception:
        return build_ppt_locally()
    finally:
        try:
            Path(ppt_path).unlink(missing_ok=True)
        except OSError:
            pass

@app.local_entrypoint()
def main():

    from pathlib import Path

    ppt_bytes = create_ppt.remote(
        "Demo Presentation",
        [
            "Introduction",
            "Results",
            "Conclusion"
        ]
    )

    output_dir = Path("sandbox_outputs")
    output_dir.mkdir(exist_ok=True)

    output_file = output_dir / "officecli_demo.pptx"

    with open(output_file, "wb") as f:
        f.write(ppt_bytes)

    print(f"Saved to: {output_file.resolve()}")
