import modal

app = modal.App("sandbox-learning")

image = (
    modal.Image.debian_slim()
    .pip_install(
        "openai",
        "reportlab",
        "python-docx",
        "openpyxl",
        "python-pptx",
    )
)


def _normalize_export_payload(payload):
    """
    Normalize legacy payloads into the generic export contract.

    The backend is moving from a presentation-specific flow to a general
    document export path so the Deep Agent can eventually export its own
    reasoning output as PPTX, DOCX, XLSX, or PDF without new sandbox actions.
    """

    action = payload.get("action")

    if action == "export_document":
        return payload

    if action == "create_presentation":
        return {
            "action": "export_document",
            "document_type": "pptx",
            "content": {
                "title": payload["title"],
                "slides": payload["slides"],
            },
        }

    return payload


def _create_ppt_document(content):
    """
    Keep PowerPoint generation on the existing OfficeCLI-backed function.

    This preserves current behavior while the export system becomes generic.
    If the remote OfficeCLI runtime is stale or fails in local development,
    fall back to a local PPTX generator so the export API still works.
    """

    title = content.get("title", "Untitled Presentation")
    slides = content.get("slides", [])

    ppt_function = modal.Function.from_name(
        "officecli-create-ppt",
        "create_ppt"
    )

    try:
        file_bytes = ppt_function.remote(title, slides)
        if _ppt_has_expected_slide_count(file_bytes, slides):
            return file_bytes
        return _create_ppt_document_locally(title, slides)
    except Exception:
        return _create_ppt_document_locally(title, slides)


def _ppt_has_expected_slide_count(file_bytes, slides):
    from io import BytesIO

    from pptx import Presentation

    try:
        presentation = Presentation(BytesIO(file_bytes))
        expected_slide_count = len(slides) + 1
        return len(presentation.slides) >= expected_slide_count
    except Exception:
        return False


def _create_ppt_document_locally(title, slides):
    from io import BytesIO

    from pptx import Presentation

    presentation = Presentation()

    title_slide_layout = presentation.slide_layouts[0]
    title_slide = presentation.slides.add_slide(title_slide_layout)
    title_slide.shapes.title.text = title

    if len(title_slide.placeholders) > 1:
        subtitle = title_slide.placeholders[1]
        subtitle.text = "Generated by RAG Document Analyzer"

    bullet_slide_layout = presentation.slide_layouts[1]

    for slide_text in slides:
        slide = presentation.slides.add_slide(bullet_slide_layout)
        slide.shapes.title.text = slide_text

        if len(slide.placeholders) > 1:
            text_frame = slide.placeholders[1].text_frame
            text_frame.text = slide_text

    if not slides:
        slide = presentation.slides.add_slide(bullet_slide_layout)
        slide.shapes.title.text = "Summary"
        if len(slide.placeholders) > 1:
            slide.placeholders[1].text_frame.text = title

    buffer = BytesIO()
    presentation.save(buffer)
    buffer.seek(0)
    return buffer.read()


def _create_docx_document(content):
    from io import BytesIO

    from docx import Document

    document = Document()

    title = content.get("title")
    if title:
        document.add_heading(title, level=0)

    sections = content.get("sections", [])
    paragraphs = content.get("paragraphs", [])
    text = content.get("text")

    if sections:
        for section in sections:
            heading = section.get("heading")
            body = section.get("body")
            body_paragraphs = section.get("paragraphs", [])

            if heading:
                document.add_heading(heading, level=1)

            if isinstance(body, str) and body.strip():
                document.add_paragraph(body)

            for paragraph in body_paragraphs:
                if paragraph:
                    document.add_paragraph(paragraph)
    elif paragraphs:
        for paragraph in paragraphs:
            if paragraph:
                document.add_paragraph(paragraph)
    elif isinstance(text, str) and text.strip():
        for paragraph in text.split("\n\n"):
            cleaned_paragraph = paragraph.strip()
            if cleaned_paragraph:
                document.add_paragraph(cleaned_paragraph)

    buffer = BytesIO()
    document.save(buffer)
    buffer.seek(0)
    return buffer.read()


def _create_xlsx_document(content):
    from io import BytesIO

    from openpyxl import Workbook

    workbook = Workbook()

    sheets = content.get("sheets")
    if not sheets:
        sheets = [
            {
                "name": content.get("title", "Sheet1"),
                "rows": content.get("rows", []),
            }
        ]

    for index, sheet_data in enumerate(sheets):
        if index == 0:
            worksheet = workbook.active
        else:
            worksheet = workbook.create_sheet()

        worksheet.title = sheet_data.get("name", f"Sheet{index + 1}")

        for row in sheet_data.get("rows", []):
            worksheet.append(row)

    buffer = BytesIO()
    workbook.save(buffer)
    buffer.seek(0)
    return buffer.read()


def _create_pdf_document(content):
    from io import BytesIO

    from reportlab.lib.styles import getSampleStyleSheet
    from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer

    buffer = BytesIO()
    document = SimpleDocTemplate(buffer)
    styles = getSampleStyleSheet()
    story = []

    title = content.get("title")
    if title:
        story.append(Paragraph(title, styles["Title"]))
        story.append(Spacer(1, 12))

    sections = content.get("sections", [])
    paragraphs = content.get("paragraphs", [])
    text = content.get("text")

    if sections:
        for section in sections:
            heading = section.get("heading")
            body = section.get("body")
            body_paragraphs = section.get("paragraphs", [])

            if heading:
                story.append(Paragraph(heading, styles["Heading2"]))
                story.append(Spacer(1, 8))

            if isinstance(body, str) and body.strip():
                story.append(Paragraph(body.replace("\n", "<br/>"), styles["BodyText"]))
                story.append(Spacer(1, 8))

            for paragraph in body_paragraphs:
                if paragraph:
                    story.append(Paragraph(paragraph.replace("\n", "<br/>"), styles["BodyText"]))
                    story.append(Spacer(1, 8))
    elif paragraphs:
        for paragraph in paragraphs:
            if paragraph:
                story.append(Paragraph(paragraph.replace("\n", "<br/>"), styles["BodyText"]))
                story.append(Spacer(1, 8))
    elif isinstance(text, str) and text.strip():
        for paragraph in text.split("\n\n"):
            cleaned_paragraph = paragraph.strip()
            if cleaned_paragraph:
                story.append(Paragraph(cleaned_paragraph.replace("\n", "<br/>"), styles["BodyText"]))
                story.append(Spacer(1, 8))

    document.build(story)
    buffer.seek(0)
    return buffer.read()


def _dispatch_export(document_type, content):
    if document_type == "pptx":
        return _create_ppt_document(content)

    if document_type == "docx":
        return _create_docx_document(content)

    if document_type == "xlsx":
        return _create_xlsx_document(content)

    if document_type == "pdf":
        return _create_pdf_document(content)

    raise ValueError(f"Unsupported document type: {document_type}")


def process_payload(payload):
    """
    Shared export handler for both Modal execution and local backend fallback.

    This lets local API development keep working even if the deployed Modal
    function has not been redeployed yet with the latest export dispatcher.
    """

    payload = _normalize_export_payload(payload)
    action = payload.get("action")

    # ----------------------------------
    # TEST
    # ----------------------------------

    if action == "test":
        return {
            "status": "sandbox_alive"
        }

    # ----------------------------------
    # EXPORT DOCUMENT
    # ----------------------------------

    if action == "export_document":
        document_type = payload["document_type"]
        content = payload.get("content", {})

        return {
            "status": "success",
            "file_bytes": _dispatch_export(document_type, content)
        }

    raise ValueError(
        f"Unknown action: {action}"
    )


@app.function(image=image)
def analyze_file(payload):
    return process_payload(payload)


@app.local_entrypoint()
def main():

    result = analyze_file.remote(
        {
            "action": "test"
        }
    )

    print(result)
